[env:esp32-a1s-audiokit]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.partitions = huge_app.csv
board_build.flash_mode = dio

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -std=c++14

lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.1.3
    https://github.com/pschatzmann/arduino-audio-driver.git#v0.1.4
    ArduinoJson@6.21.2